# Generated by Django 5.2.5 on 2025-08-20 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('context', models.TextField(blank=True)),
                ('create_ed', models.DateTimeField(auto_now_add=True)),
                ('update_ed', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('is_bool', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0)),
                ('carmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.carmodel')),
            ],
        ),
    ]
